#!/bin/bash
# MLPerf GPT-OSS-20B configuration for MI355X (1x8x1).

export DGXSYSTEM=MI355X_1x8x1
export GPUS_PER_NODE=8
export NNODES=1
export NODE_RANK=0
export MASTER_ADDR=localhost
export MASTER_PORT=29501

export PRIMUS_PATH=/workspace/Primus
export PRIMUS_MLPERF=1
export PYTHONPATH="${PRIMUS_PATH}:${PRIMUS_PATH}/third_party/Megatron-LM:${PYTHONPATH}"
export EXP=${PRIMUS_PATH}/examples/mlperf/gpt_oss_20b/configs/MI355/gpt_oss_20B-FP8-turbo-attn-mlperf-pretrain.yaml
export DATA_PATH=/data

# MXFP4 + de-oscillation:
#   export EXP=${PRIMUS_PATH}/examples/mlperf/gpt_oss_20b/configs/MI355/gpt_oss_20B-MXFP4-deosc-mlperf-pretrain.yaml
#   export MLLOG_LOWEST_NUMERICAL_PRECISION_LINEAR=mxfp4

export PRIMUS_MICRO_BATCH_SIZE=4
export PRIMUS_GLOBAL_BATCH_SIZE=32
export PRIMUS_LR=8.0e-4
export PRIMUS_MIN_LR=8.0e-5
export PRIMUS_TRAIN_ITERS=1200000
export PRIMUS_LR_WARMUP_ITERS=128
export PRIMUS_LR_DECAY_ITERS=$((PRIMUS_TRAIN_ITERS - PRIMUS_LR_WARMUP_ITERS))
export EVAL_ITERS=$((1024 / PRIMUS_GLOBAL_BATCH_SIZE))
export EVAL_SAMPLES_INTERVAL=12288
export PRIMUS_EVAL_INTERVAL=$((EVAL_SAMPLES_INTERVAL / PRIMUS_GLOBAL_BATCH_SIZE))

export PRIMUS_TP=1
export PRIMUS_PP=1
export PRIMUS_EP=1

export PRIMUS_TURBO_FUSED_WGRAD_ACCUM="${PRIMUS_TURBO_FUSED_WGRAD_ACCUM:-1}"
export PRIMUS_NUM_WORKERS="${PRIMUS_NUM_WORKERS:-2}"
export PRIMUS_GRAD_REDUCE_IN_BF16=true
export USE_TURBO_RMS_NORM=true
export USE_TURBO_NORM_TE_LINEAR=true

# 0=RTE (default), 1=RZ, 2=stochastic. Consumed by Turbo MXFP4 HIP/FlyDSL quant
# on gpt-oss-mxfp4 branches; ignored by Turbo builds that do not read it.
export PRIMUS_TURBO_MXFP4_SCALE_ROUNDING="${PRIMUS_TURBO_MXFP4_SCALE_ROUNDING:-0}"

export HSA_ENABLE_INTERRUPT=0
export HSA_NO_SCRATCH_RECLAIM=1
export HSA_ENABLE_SDMA=1
export GPU_MAX_HW_QUEUES=2
export CUDA_DEVICE_MAX_CONNECTIONS=1
export HIP_FORCE_DEV_KERNARG=1
export HSA_FORCE_FINE_GRAIN_PCIE=1
export HSA_KERNARG_POOL_SIZE=12582912
export PYTORCH_ALLOC_CONF=expandable_segments:False
export ENABLE_NUMA_BINDING=1
export OMP_NUM_THREADS=1
export PYTHONWARNINGS=ignore
export TOKENIZERS_PARALLELISM=false

export NCCL_MIN_P2P_NCHANNELS=32
export NCCL_MIN_CTAS=32
export NCCL_NCHANNELS_PER_NET_PEER=32
export NCCL_NVLS_ENABLE=0
export NCCL_CHECKS_DISABLE=1
export TORCH_NCCL_HIGH_PRIORITY=1

export USE_HIPBLASLT=1
export TORCH_BLAS_PREFER_HIPBLASLT=1
if [ -z "${HIPBLASLT_TUNING_OVERRIDE_FILE:-}" ]; then
    _tune="${PRIMUS_PATH}/examples/mlperf/gpt_oss_20b/tune_gemm_results-v26.5.txt"
    if [ -f "${_tune}" ]; then
        export HIPBLASLT_TUNING_OVERRIDE_FILE="${_tune}"
    fi
fi

export NVTE_FLASH_ATTN=0
export NVTE_ROCM_ENABLE_MXFP8=0
export NVTE_USE_CAST_TRANSPOSE_TRITON=0
export NVTE_USE_OPTIMIZED_HIPIFIED_CAST_TRANSPOSE=1
export NVTE_DEBUG=0
export NVTE_DEBUG_LEVEL=0
export NVTE_LOG_FUSED_ATTN_CONFIG=0
export NVTE_LOG_CK_CONFIG=0
export CK_FUSED_ATTN_LOG_CONFIG=0

export LOG_INTERVAL=999999
export ENABLE_MLLOG=1
export MLLOG_TRAIN_LOSS_LOG_FREQ=0
export MLLOG_TARGET_EVAL_LOSS=3.34
export TARGET_EVAL_LOSS=3.34
export MLLOG_OUTPUT_FILE=/results/mlperf_logging.out
export MLLOG_SAVE_TO_FILE=0
export MLLOG_SUBMISSION_BENCHMARK=gpt_oss_20b
export MLLOG_SUBMISSION_DIVISION=closed
export MLLOG_SUBMISSION_ORG=AMD
export MLLOG_SUBMISSION_PLATFORM=MI355X
export MLLOG_TENSOR_PARALLELISM=1
export MLLOG_PIPELINE_PARALLELISM=1
export MLLOG_CONTEXT_PARALLELISM=1
export MLLOG_EXPERT_PARALLELISM=1
export MLLOG_MICRO_BATCH_SIZE=4
MLLOG_CONFIG_FILENAME=$(basename "${BASH_SOURCE[0]}")
export MLLOG_CONFIG_FILENAME
export MLLOG_LOWEST_NUMERICAL_PRECISION_LINEAR="${MLLOG_LOWEST_NUMERICAL_PRECISION_LINEAR:-fp8}"

export MOE_SKIP_IDENTITY_SORT=1
export PRIMUS_FUSED_RESIDUAL_NORM=1
export PRIMUS_MOE_SWIGLU_NOCAT=1
export MLLOG_BLOCK_TPUT_LOG=0
export MLPERF_VERBOSE_LOGS=${MLPERF_VERBOSE_LOGS:-0}
